config/routes.rb
Rails.application.routes.draw do

 resources :sessions 
 resources :users do
 resources :projectowners
 end
 
 root 'sessions#new'
 
 
 get 'login' =>'sessions#new' 
 
  get 'logout'=>'sessions#destroy'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/projectowner.rb
class Projectowner < ApplicationRecord
	has_many :tasks,dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :projectowner

end

app/models/user.rb
class User < ApplicationRecord
mount_uploader :image, ImageUploader

	has_secure_password

	has_many :projectowners, dependent: :destroy

	validates :firstname, presence: true, length: { maximum: 50}
	validates :lastname, presence: true, length: { maximum: 50}
	validates :email, presence: true, length: { maximum: 200},  
	                        
	                         uniqueness: { case_sensitive: false }

	      
	      validates :password, length: { minimum: 4 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   include SessionsHelper
end

app/controllers/projectowners_controller.rb
class ProjectownersController < ApplicationController

	def new

	end

	def create
	@user = User.find_by(id: current_user.id)

	@user.projectowners.build(projectowner_params)

   if @user.save

   	flash[:sucess] = "Project created "

redirect_to user_path(current_user)

	else

   render 'new'

	end
end
private
def projectowner_params

params.require(:projectowner).permit(:name,:startdate,:enddate)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new

   end
   def create
     user = User.find_by(email: params[:session][:email])


      if user && user.authenticate(params[:session][:password])
        flash[:notice] = "Login Successfully"
        log_in user
      redirect_to new_user_projectowner_path(user)
  #user_path(user)
      else

      flash.now[:danger] = 'Invalid Email / Password Combination'

      render 'new'
            
      end
  end

  def destroy
    log_out
    redirect_to root_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_user,only: [:index,:show]

  def index

    @users=User.all.where('id!=?', current_user)
  end

  def new
    @user=User.new
  end

  def show
    @user=User.find_by(id: session[:user_id])
  end

  def create
    @user = User.new(user_params)
 
    if @user.save
      
      flash[:notice] = "Signup Successfully"
      log_in @user
      redirect_to new_session_path
    
    else
      render 'new'
    end
  end
  
 


  private

    def user_params
      params.require(:user).permit(:firstname,:lastname,:image,:email,:password,:devid )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projectowners_helper.rb
module ProjectownersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
 def log_in(user)
	  session[:user_id] = user.id
	end

	def current_user
	  @current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
	  !current_user.nil?
	end

	def log_out
	  session.delete(:user_id)
	  session[:user_id] = nil
	  @current_user = nil
	end
	def require_user
	  redirect_to '/login' unless current_user
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projectowners/new.html.erb
<h2>CREATE PROJECT</h2>
<%= form_for(:projects, url: user_projectowners_path)  do |f| %>

<%= f.label :name  %> 
<%= f.text_field :name , placeholder: "name" %><br><br>

<%= f.label :startdate %>
<%= f.date_field :startdate , placeholder: "startdate" %><br><br>

<%= f.label :enddate %>
<%= f.date_field :enddate , placeholder: "enddate" %><br><br>


<%= f.submit "Create project" %>
<% end %>

app/views/users/_form.html.erb
<center>
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
<div id="error_explanation">
  <h3>
<%= pluralize(@user.errors.count,"error") %>
prohibited this user from being saved:
</h2>
</div>
<%end%>

<p>
    <%= f.label :firstname %>
    <%= f.text_field :firstname , placeholder: "Firstname" %>
  </p>

  <p>
    <%= f.label :lastname %>
    <%= f.text_field :lastname , placeholder: "Lastname" %>
<p>
  
  <p>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "Email" %>
  </p>

  <p>
    <%= f.label :devid %>
    <%= f.text_field :devid, placeholder: "Enter the Question" %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password , placeholder: "Password" %>
  </p>
  
  <p>
    <%= f.submit "Sign Up",class: "btn btn-primary" %>
  </p>
  
<%end%>

</center>

app/views/users/index.html.erb
<center>
<div>
<%= link_to "Logout!", logout_path %>
<center>
	

<% @users.each do |f| %>
 <tr> 
  <td><%= f.firstname %>
  <%= f.lastname %>
 </td>
</tr>
<% end %>
</center>
</div>
</center>

app/views/users/new.html.erb
<p>Already have an account? <%= link_to "Sign in!",  new_session_path %></p>

<center>

<h1>SIGN UP</h1>





<%= render 'form' %>
 </center>

app/views/users/show.html.erb
<center>

<h3> Profile: <%= current_user.firstname %> <%= current_user.lastname %> </h3>



<h2>Show Project</h2>

<% @projectowners.each do|projectowner| %>
<%= projectowner.name %>
<%= projectowner.startdate %>
<%= projectowner.enddate %>
<%= link_to "Assign to Developer" %> 

<%= link_to "Logout!", logout_path %>
<% end %>
</center>